// Generated by scripts/content/build-curriculum.mjs from data/staging/curriculum/subject-terms.jsonl.
// Do not edit by hand. See docs/CURRICULUM.md (term policy).
export const CATALOG_TERMS = {
  "$comment": "Generated by scripts/content/build-curriculum.mjs from subject-terms.jsonl. Subjects not listed use `default`. A subject leaves a term only on verified evidence. Do not edit by hand.",
  "default": {
    "terms": [
      "t1",
      "t2"
    ],
    "terms_status": "unverified"
  },
  "subjects": {}
};
