// ============================================================================
// Jazira Assistant — conversation store.
//
// Conversations are rows of `chat_history` (RLS: own rows only) grouped by
// `session_id`. The server is the source of truth (every reply is stored by
// POST /api/chat); nothing is kept in localStorage any more.
//
//   Pure helpers (no I/O) — shared by the route handlers, the UI and tests:
//     isValidSessionId, newSessionId, prepareChatInput, groupSessions,
//     deriveTitle, bucketSessions, CHAT_LIMITS
//   Client API (fetch → /api/chat-history, same origin):
//     listSessions({ before, limit, signal }) → { sessions, nextCursor }
//     getSession(id, { signal })            → { id, messages, truncated }
//     deleteSession(id)                     → true
//   Errors thrown by the client API carry a stable `code`:
//     "not_authenticated" | "unavailable" | "invalid_argument" | "network" | "unknown"
// ============================================================================

export const CHAT_LIMITS = Object.freeze({
  maxMessageChars: 4000, // one user message (the composer enforces the same limit)
  maxHistoryTurns: 24, // earlier messages sent to the model as context
  maxHistoryChars: 24000, // total characters of that context
  maxReplyChars: 8000, // a stored assistant reply used as context is cut here
  maxBodyBytes: 256 * 1024, // request body cap for POST /api/chat
});

// session ids are generated by the client (UUID); legacy ids ("c_…") also pass.
const SESSION_ID_RE = /^[A-Za-z0-9_-]{1,100}$/;

export const isValidSessionId = (value) => typeof value === "string" && SESSION_ID_RE.test(value);

export function newSessionId() {
  try {
    if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
  } catch {}
  return `s_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`;
}

const clean = (text) => String(text ?? "").replace(/\r\n?/g, "\n");

/**
 * Validate and bound a chat request body's `messages` for the model.
 *   → { ok: true, text, history: [{ role: "user"|"assistant", content }] }
 *   | { ok: false, error: "invalid_request" | "empty_message" | "message_too_long" }
 * - the last message must be the user's (it is the one being sent)
 * - earlier messages: user/assistant only, empty ones dropped, consecutive
 *   same-role turns merged, the oldest dropped first to fit the budgets, and
 *   the context always starts with a user turn.
 */
export function prepareChatInput(messages, limits = CHAT_LIMITS) {
  if (!Array.isArray(messages) || messages.length === 0 || messages.length > 400) return { ok: false, error: "invalid_request" };
  const last = messages[messages.length - 1];
  if (!last || typeof last !== "object" || last.role !== "user" || typeof last.content !== "string") {
    return { ok: false, error: "invalid_request" };
  }
  const text = clean(last.content).trim();
  if (!text) return { ok: false, error: "empty_message" };
  if (text.length > limits.maxMessageChars) return { ok: false, error: "message_too_long" };

  const prior = [];
  for (const m of messages.slice(0, -1)) {
    if (!m || typeof m !== "object" || (m.role !== "user" && m.role !== "assistant") || typeof m.content !== "string") continue;
    const cap = m.role === "user" ? limits.maxMessageChars : limits.maxReplyChars;
    const content = clean(m.content).trim().slice(0, cap);
    if (!content) continue;
    const prev = prior[prior.length - 1];
    if (prev && prev.role === m.role) prev.content = `${prev.content}\n\n${content}`.slice(0, cap);
    else prior.push({ role: m.role, content });
  }

  // Newest first until a budget is hit.
  const history = [];
  let chars = 0;
  for (let i = prior.length - 1; i >= 0; i--) {
    const m = prior[i];
    if (history.length >= limits.maxHistoryTurns || chars + m.content.length > limits.maxHistoryChars) break;
    history.unshift(m);
    chars += m.content.length;
  }
  while (history.length && history[0].role !== "user") history.shift();
  // The new user turn follows, so the context must end with the assistant.
  while (history.length && history[history.length - 1].role === "user") history.pop();
  return { ok: true, text, history };
}

/** Short one-line title from a user message. */
export function deriveTitle(text, max = 80) {
  const t = clean(text)
    .replace(/```[\s\S]*?(```|$)/g, " ")
    .replace(/[*_`#>]+/g, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!t) return "";
  return t.length > max ? `${t.slice(0, max - 1).trimEnd()}…` : t;
}

/**
 * Group user-message rows (newest first: { session_id, created_at }) into
 * conversations ordered by latest activity.
 *   → { sessions: [{ id, lastAt, firstSeenAt }], nextCursor }
 * `scanFull` = the scan hit its row cap, so older rows may exist.
 * Cursor rule (keyset on created_at): with more sessions than `limit` in the
 * scan, continue strictly before the last returned session's latest activity;
 * with a full scan but few sessions, continue before the oldest scanned row.
 * Pages can repeat a session that spans pages — callers merge by id.
 */
export function groupSessions(rows, { limit = 20, scanFull = false } = {}) {
  const order = [];
  const byId = new Map();
  for (const r of rows || []) {
    const id = r?.session_id;
    if (!id || !r.created_at) continue;
    let s = byId.get(id);
    if (!s) {
      s = { id, lastAt: r.created_at, firstSeenAt: r.created_at };
      byId.set(id, s);
      order.push(s);
    } else if (r.created_at < s.firstSeenAt) {
      s.firstSeenAt = r.created_at;
    }
  }
  if (order.length > limit) {
    const sessions = order.slice(0, limit);
    return { sessions, nextCursor: sessions[sessions.length - 1].lastAt };
  }
  const oldest = rows?.length ? rows[rows.length - 1].created_at : null;
  return { sessions: order, nextCursor: scanFull && oldest ? oldest : null };
}

/** Merge a new page of sessions into a list (dedupe by id, keep newest activity first). */
export function mergeSessions(list, page) {
  const seen = new Map(list.map((s) => [s.id, s]));
  const out = [...list];
  for (const s of page) {
    if (seen.has(s.id)) continue;
    seen.set(s.id, s);
    out.push(s);
  }
  return out.sort((a, b) => (a.lastAt < b.lastAt ? 1 : a.lastAt > b.lastAt ? -1 : 0));
}

const dayStart = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();

/**
 * Split sessions into "today" / "yesterday" / "week" / "older" buckets by the
 * viewer's local calendar day. → [{ key, items }] (empty buckets omitted)
 */
export function bucketSessions(sessions, now = new Date()) {
  const today = dayStart(now);
  const DAY = 86400000;
  const buckets = { today: [], yesterday: [], week: [], older: [] };
  for (const s of sessions) {
    const t = new Date(s.lastAt).getTime();
    if (Number.isNaN(t)) continue;
    if (t >= today) buckets.today.push(s);
    else if (t >= today - DAY) buckets.yesterday.push(s);
    else if (t >= today - 7 * DAY) buckets.week.push(s);
    else buckets.older.push(s);
  }
  return ["today", "yesterday", "week", "older"].filter((k) => buckets[k].length).map((key) => ({ key, items: buckets[key] }));
}

// ── client API ──────────────────────────────────────────────────────────────

function apiError(code, cause) {
  const e = new Error(code);
  e.name = "ChatStoreError";
  e.code = code;
  if (cause) e.cause = cause;
  return e;
}

async function call(url, init) {
  let res;
  try {
    res = await fetch(url, { cache: "no-store", credentials: "same-origin", ...init });
  } catch (err) {
    if (err?.name === "AbortError") throw apiError("aborted", err);
    throw apiError("network", err);
  }
  let body = null;
  try {
    body = await res.json();
  } catch {}
  if (res.ok) return body;
  if (res.status === 401) throw apiError("not_authenticated");
  if (res.status === 503) throw apiError("unavailable");
  if (res.status === 400) throw apiError("invalid_argument");
  throw apiError("unknown", body);
}

/** One page of past conversations, newest activity first. */
export async function listSessions({ before, limit = 20, signal } = {}) {
  const q = new URLSearchParams({ limit: String(limit) });
  if (before) q.set("before", before);
  const body = await call(`/api/chat-history?${q}`, { signal });
  return { sessions: Array.isArray(body?.sessions) ? body.sessions : [], nextCursor: body?.nextCursor || null };
}

/** Messages of one conversation, oldest first (the latest 200). */
export async function getSession(id, { signal } = {}) {
  if (!isValidSessionId(id)) throw apiError("invalid_argument");
  const body = await call(`/api/chat-history?session=${encodeURIComponent(id)}`, { signal });
  return { id, messages: Array.isArray(body?.messages) ? body.messages : [], truncated: Boolean(body?.truncated) };
}

/** Permanently delete one conversation (all its rows). */
export async function deleteSession(id) {
  if (!isValidSessionId(id)) throw apiError("invalid_argument");
  await call(`/api/chat-history?session=${encodeURIComponent(id)}`, { method: "DELETE" });
  return true;
}
