// ============================================================================
// Curriculum outline reader (server only) — docs/CONTENT_ENGINE.md §2.5, §7.
//
// The outline layer (units, lessons, book pages, term membership, resources)
// is generated by scripts/content/build-curriculum.mjs into
// src/content/curriculum/outline/<stage>/<grade>[-<track>].json, one file per
// catalog leaf. This module loads a leaf lazily (never the whole corpus) and
// serves the node-tree interface pinned by tests/fixtures/content/outline-tree.json:
//
//   const tree = await loadOutline("middle/grade-1")      // sync tree object
//   tree.nodeById(id) · tree.outlineFor(leaf) · tree.subjectOutline(subjectId)
//   tree.lessonsUnder(id) · tree.subjectTerms(subjectId) · tree.eligibleLessons(scope)
//   tree.resourcesFor(subjectId) · tree.childrenOf(id)
//
// plus async shortcuts that resolve the leaf from any node id:
//   await outlineFor(leaf) · subjectOutline(id) · nodeById(id) · lessonsUnder(id) · subjectTerms(id)
//
// Leaf files are addressed only through catalog leaf slugs (allow-list), never
// through a path built from request input. The lazy JSON import is resolved by
// the bundler (Next/webpack, Vitest/Vite); plain Node scripts read the outline
// files themselves and pass the data to `createOutlineTree`.
// ============================================================================

import { allLeaves } from "./curriculum.js";

const TERM_OK = new Set(["verified", "inferred"]);
const TERM_SETS = { t1: ["t1"], t2: ["t2"], both: ["t1", "t2"] };
const hasTerm = (node, t) => (TERM_SETS[node.term] ?? []).includes(t);
const byOrder = (a, b) => a.order - b.order || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);

/** Catalog leaf slugs ("middle/grade-1", "high-school/grade-2/general", …). */
export const OUTLINE_LEAVES = Object.freeze(allLeaves().map((l) => l.slug.join("/")));
const LEAF_SET = new Set(OUTLINE_LEAVES);

/** Outline file stem of a leaf: middle/grade-1 → middle/grade-1, high-school/grade-2/general → high-school/grade-2-general. */
export function outlineFile(leaf) {
  const [stage, grade, track] = String(leaf).split("/");
  return track ? `${stage}/${grade}-${track}` : `${stage}/${grade}`;
}

/** The catalog leaf a node id belongs to (longest leaf prefix), or null. */
export function leafOf(nodeId) {
  const id = String(nodeId ?? "").split("@")[0];
  let best = null;
  for (const leaf of OUTLINE_LEAVES) {
    if ((id === leaf || id.startsWith(`${leaf}/`)) && (!best || leaf.length > best.length)) best = leaf;
  }
  return best;
}

/**
 * Parse a curriculum scope: `<node id>[@t1|@t2|@year]` → { nodeId, term }.
 * (`prep:` and `weak:` scopes are handled by the exam engine, not here.)
 */
export function parseScope(scope) {
  const m = /^([a-z0-9-]+(?:\/[a-z0-9-]+){0,5})(?:@(t1|t2|year))?$/.exec(String(scope ?? ""));
  return m ? { nodeId: m[1], term: m[2] ?? null } : null;
}

/**
 * Build the sync node-tree object from outline data
 * ({ leaf?, nodes, subject_terms?, resources? }).
 */
export function createOutlineTree(data) {
  const nodes = Array.isArray(data?.nodes) ? data.nodes : [];
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const kids = new Map();
  for (const n of nodes) {
    if (!n.parent_id) continue;
    if (!kids.has(n.parent_id)) kids.set(n.parent_id, []);
    kids.get(n.parent_id).push(n);
  }
  for (const list of kids.values()) list.sort(byOrder);
  const terms = Array.isArray(data?.subject_terms) ? data.subject_terms : [];
  const resources = Array.isArray(data?.resources) ? data.resources : [];

  const childrenOf = (id) => kids.get(id) ?? [];

  function lessonsUnder(id) {
    const start = byId.get(id);
    if (!start) return [];
    if (start.kind === "lesson") return [start.id];
    const out = [];
    const walk = (nid) => {
      for (const c of kids.get(nid) ?? []) {
        if (c.kind === "term") continue;
        if (c.kind === "lesson") out.push(c.id);
        walk(c.id);
      }
    };
    walk(start.id);
    return out;
  }

  function subjectOutline(subjectNodeId) {
    const s = byId.get(subjectNodeId);
    if (!s || s.kind !== "subject") return null;
    const build = (id) => ({ id, children: (kids.get(id) ?? []).filter((c) => c.kind !== "term").map((c) => build(c.id)) });
    return build(s.id);
  }

  function outlineFor(leafSlug) {
    const leaf = Array.isArray(leafSlug) ? leafSlug.join("/") : String(leafSlug ?? "");
    if (!byId.has(leaf)) return null;
    return { leaf, subjects: (kids.get(leaf) ?? []).filter((n) => n.kind === "subject").map((n) => n.id) };
  }

  /** §5.3 step 1: verified, non-opener lessons under the scope node, filtered by term. */
  function eligibleLessons(scope) {
    const s = parseScope(scope);
    if (!s || !byId.has(s.nodeId)) return [];
    const inTerm = (n, t) => hasTerm(n, t) && TERM_OK.has(n.term_status);
    return lessonsUnder(s.nodeId)
      .map((id) => byId.get(id))
      .filter((n) => n.status === "verified" && !n.unit_opener)
      .filter((n) => (s.term === "t1" || s.term === "t2" ? inTerm(n, s.term) : s.term === "year" ? inTerm(n, "t1") || inTerm(n, "t2") : true))
      .map((n) => n.id);
  }

  return {
    leaf: data?.leaf ?? null,
    nodeById: (id) => byId.get(id) ?? null,
    childrenOf: (id) => childrenOf(id).map((n) => n.id),
    outlineFor,
    subjectOutline,
    lessonsUnder,
    subjectTerms: (subjectNodeId) => terms.filter((r) => r.subject_node_id === subjectNodeId),
    resourcesFor: (subjectNodeId) => resources.filter((r) => r.subject_node_id === subjectNodeId),
    eligibleLessons,
    nodes: () => nodes,
  };
}

const cache = new Map();
const MISSING = /MODULE_NOT_FOUND|Cannot find module|Unknown variable dynamic import|Failed to load url|does not exist/i;

/**
 * Load one leaf's outline (memoized). Returns an empty tree when the leaf has
 * no generated outline yet, and null for an unknown leaf.
 */
export async function loadOutline(leafSlug) {
  const leaf = Array.isArray(leafSlug) ? leafSlug.join("/") : String(leafSlug ?? "");
  if (!LEAF_SET.has(leaf)) return null;
  if (!cache.has(leaf)) {
    // Two one-segment variables: bundlers (webpack, Vite) turn this into a
    // context over outline/*/*.json, one lazily loaded chunk per leaf.
    const [dir, name] = outlineFile(leaf).split("/");
    cache.set(
      leaf,
      import(`../content/curriculum/outline/${dir}/${name}.json`)
        .then((m) => createOutlineTree(m.default ?? m))
        .catch((e) => {
          // A leaf without a generated outline yet is an honest empty tree; anything else is a real error.
          if (!MISSING.test(`${e?.code ?? ""} ${e?.message ?? ""}`)) {
            cache.delete(leaf);
            throw e;
          }
          return createOutlineTree({ leaf, nodes: [] });
        }),
    );
  }
  return cache.get(leaf);
}

async function treeFor(nodeId) {
  const leaf = leafOf(nodeId);
  return leaf ? loadOutline(leaf) : null;
}

/** { leaf, subjects: [subject node ids in order] } or null. */
export async function outlineFor(leafSlug) {
  const tree = await loadOutline(leafSlug);
  return tree ? tree.outlineFor(leafSlug) : null;
}
/** { id, children: [...] } nested by parent in order, or null. */
export async function subjectOutline(subjectNodeId) {
  return (await treeFor(subjectNodeId))?.subjectOutline(subjectNodeId) ?? null;
}
/** The outline node, or null. */
export async function nodeById(id) {
  return (await treeFor(id))?.nodeById(id) ?? null;
}
/** Lesson ids under a node in outline order (a lesson returns itself). */
export async function lessonsUnder(id) {
  return (await treeFor(id))?.lessonsUnder(id) ?? [];
}
/** subject-terms rows (t1, t2) of a subject node. */
export async function subjectTerms(subjectNodeId) {
  return (await treeFor(subjectNodeId))?.subjectTerms(subjectNodeId) ?? [];
}
